# Generated by Django 6.0.3 on 2026-05-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_startupprofile_draft_saved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='startup_profiles', to='startups.region'),
        ),
    ]
