# Generated by Django 4.2.30 on 2026-04-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("idea", "Idea"),
                    ("mvp", "MVP"),
                    ("fundraising", "Fundraising"),
                    ("funded", "Funded"),
                    ("closed", "Closed"),
                ],
                default="idea",
                max_length=32,
            ),
        ),
    ]
