# Generated by Django 4.2.30 on 2026-04-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='users_audit_user_id_c6aa5b_idx',
            old_name='users_audit_user_actio_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='users_audit_timesta_45d1d4_idx',
            old_name='users_audit_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_uid_6000fc_idx',
            old_name='users_passw_uid_token_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='users_passw_user_id_5ee9a9_idx',
            old_name='users_passw_user_is_us_idx',
        ),
    ]
