# Generated by Django 5.2.13 on 2026-05-06 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetaudit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
