# Generated by Django 4.2.30 on 2026-05-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_org_admin'),
        ('users', '0003_alter_passwordresetaudit_user'),
    ]

    operations = [
    ]
