# Generated by Django 4.2.30 on 2026-05-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260508_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetaudit',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='revoked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
