# Generated by Django 4.2.30 on 2026-04-23 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("investors", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.project"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedstartup",
            constraint=models.UniqueConstraint(
                fields=("investor_profile", "startup_profile"),
                name="unique_saved_startup",
            ),
        ),
    ]
