# Generated by Django 4.2.30 on 2026-04-22 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedstartup',
            name='startup_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile'),
        ),
    ]
