# Generated by Django 4.2.30 on 2026-04-21 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        ('investors', '0002_investment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investorprofile')),
                ('startup_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedstartup',
            constraint=models.UniqueConstraint(fields=('investor_profile', 'startup_profile'), name='unique_saved_startup'),
        ),
    ]
