# Generated by Django 4.2.30 on 2026-05-08 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_alter_investment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('company', 'Company'), ('startup', 'Startup'), ('project', 'Project')], max_length=20)),
                ('target_id', models.CharField(max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to='investors.investorprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='saveditem',
            constraint=models.UniqueConstraint(fields=('investor', 'target_type', 'target_id'), name='unique_saved_item'),
        ),
    ]
