# Generated by Django 4.2.30 on 2026-05-16 13:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projectaudit_user'),
        ('startups', '0004_startupprofile_draft_saved_at_and_more'),
        ('investors', '0004_saveditem_saveditem_unique_saved_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('startup', 'Startup'), ('project', 'Project')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, choices=[('manual', 'Manual'), ('suggestion', 'Suggestion'), ('import', 'Import')], max_length=32, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='investors.investorprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='projects.project')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_entries', to='startups.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField()),
                ('projects_count', models.PositiveIntegerField()),
                ('total_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=18)),
                ('summary', models.JSONField(default=dict)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='investors.investorprofile')),
            ],
            options={
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['investor', '-computed_at'], name='portfolio_inv_computed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('committed', 'Committed'), ('transferred', 'Transferred'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='committed', max_length=16)),
                ('amount_committed', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('currency', models.CharField(default='UAH', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investors.investorprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['investor', 'status'], name='investment_inv_status_idx'), models.Index(fields=['project'], name='investment_project_idx')],
            },
        ),
    ]
